#!/bin/zsh
# Publish downloads/ (catalogue SQLite + OCR text bundle) as a new GitHub release. The site links to
# https://github.com/kmlawson/japan-internal-affairs/releases/latest/download/<file>, so the newest release is what readers get.
set -e
cd "$(dirname "$0")"
cp catalog.sqlite downloads/japan-internal-affairs-catalog.sqlite
TAG="data-$(date +%Y-%m-%d)"
gh release create "$TAG" downloads/japan-internal-affairs-catalog.sqlite downloads/japan-internal-affairs-ocr-text.jsonl.gz \
  -R kmlawson/japan-internal-affairs --title "Data downloads, $(date '+%-d %B %Y')" \
  --notes "Catalogue database and all OCR text for the site. Summaries, names and dates were generated by language models from OCR text and may contain errors. Public domain U.S. government records."
echo "published $TAG"
