"""Write remaining.md: an overview of the files that are not yet catalogued (placeholder entries in data.js).

Run after build_db.py:  python3 remaining.py
Lists totals, pages by period, pages by theme (decimal groups below), every decimal with its files, and the
full file list with page counts, so the next cataloguing batch can be picked from it. Rebuilt from data.js
every time, so it is always current.
"""
import os, re, json, datetime

WEB = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(WEB, "data.js"), encoding="utf-8").read()
D = json.loads(src[src.index("["):src.index(";\nwindow.CATALOG_EXPECTED")])
SK = [x for x in D if x.get("sk")]
CAT = [x for x in D if not x.get("sk")]

# themes: first matching decimal prefix wins (order matters)
THEMES = [
    ("Politics and government", r"^894\.0"),
    ("Public order, health and regulation (incl. residence and travel of foreigners)", r"^894\.1"),
    ("Military", r"^894\.2"),
    ("Naval and shipping visits", r"^894\.3"),
    ("Social, cultural and education", r"^894\.4"),
    ("Labour", r"^894\.504"),
    ("Patents and copyrights", r"^894\.54"),
    ("Economy and finance", r"^894\.5"),
    ("Fisheries", r"^894\.628"),
    ("Industry, resources, manufacturing and agriculture", r"^894\.6"),
    ("Communications and transport", r"^894\.7"),
    ("Merchant shipping and navigation", r"^894\.8"),
    ("Press and science", r"^894\.9"),
    ("Taiwan, Korea, Kwantung and other territories", r"^894[A-Z]\."),
    ("Outside 894", r""),
]


def theme(dec):
    return next(name for name, rx in THEMES if re.search(rx, dec))


def years(t):
    ys = [int(y) for y in re.findall(r"\b19[1-5]\d\b", t)]
    return (min(ys), max(ys)) if ys else None


def era(x):
    y = years(x["t"])
    if not y: return "Undated in title"
    if y[1] <= 1941: return "Pre-war (to 1941)"
    if y[0] >= 1945: return "Occupation (1945-49)"
    if y[0] >= 1941 and y[1] <= 1945: return "Wartime (1941-45)"
    return "Spans several periods"


def subject_of(t):  # the file title without its decimal number and date range
    t = re.sub(r"^\S+\s+", "", t)
    return re.sub(r",?\s*(January|February|March|April|May|June|July|August|September|October|November|December)\b.*$", "", t).strip(" ,.")


P = lambda xs: sum(x["pg"] for x in xs)
total = P(D)
out = [f"# Uncatalogued files: overview",
       f"_Generated by remaining.py from data.js on {datetime.date.today().isoformat()}. Re-run after each cataloguing batch._", "",
       f"- Catalogued: **{len(CAT):,} files, {P(CAT):,} pages** ({100 * P(CAT) / total:.1f}%)",
       f"- Uncatalogued: **{len(SK):,} files, {P(SK):,} pages** ({100 * P(SK) / total:.1f}%)", ""]

out += ["## By size", "", "| Pages per file | Files | Pages |", "|---|---:|---:|"]
for a, b in [(1, 49), (50, 99), (100, 199), (200, 299), (300, 499), (500, 10 ** 9)]:
    s = [x for x in SK if a <= x["pg"] <= b]
    if s: out.append(f"| {a}–{b if b < 10 ** 9 else '+'} | {len(s)} | {P(s):,} |")

out += ["", "## By period (from the dates in file titles)", "", "| Period | Files | Pages |", "|---|---:|---:|"]
for e in ["Pre-war (to 1941)", "Wartime (1941-45)", "Occupation (1945-49)", "Spans several periods", "Undated in title"]:
    s = [x for x in SK if era(x) == e]
    if s: out.append(f"| {e} | {len(s)} | {P(s):,} |")

out += ["", "## By theme", "", "| Theme | Files | Pages |", "|---|---:|---:|"]
by_theme = {}
for x in SK: by_theme.setdefault(theme(x["dec"]), []).append(x)
for name, xs in sorted(by_theme.items(), key=lambda kv: -P(kv[1])):
    out.append(f"| {name} | {len(xs)} | {P(xs):,} |")

out += ["", "## By decimal", "", "| Decimal | Subject | Files | Pages | Years |", "|---|---|---:|---:|---|"]
by_dec = {}
for x in SK: by_dec.setdefault(x["dec"], []).append(x)
for dec, xs in sorted(by_dec.items(), key=lambda kv: -P(kv[1])):
    ys = [y for y in (years(x["t"]) for x in xs) if y]
    span = f"{min(y[0] for y in ys)}–{max(y[1] for y in ys)}" if ys else "undated"
    out.append(f"| {dec} | {subject_of(xs[0]['t'])[:70]} | {len(xs)} | {P(xs):,} | {span} |")

out += ["", "## All uncatalogued files", "", "Theme, then pages (largest first). `id` is the site id (`json-merged/<id>/` when catalogued); `pdf` is the file name for `--only` lists.", "",
        "| Pages | Theme | Title | id |", "|---:|---|---|---|"]
for x in sorted(SK, key=lambda x: (theme(x["dec"]), -x["pg"])):
    out.append(f"| {x['pg']} | {theme(x['dec']).split(' (')[0]} | {x['t']} | `{x['id']}` |")

out += ["", "## Making a batch", "",
        "Write the PDF names (`f` in data.js) of the chosen files to a list, then run two workers, e.g.:", "",
        "```", "python3 catalog_merged.py --backend agy --model gemini-3.8-flash-high --only only-X.txt \\",
        "    --ocr ../merged/ocr,../merged/ocr-batch3,../merged/ocr-batch4", "# second worker: same command with --reverse",
        "```", "Then `python3 build_db.py && python3 build_sets.py && python3 build_spotlight.py && python3 remaining.py`, "
        "and rebuild the full-text index (fulltext-build/) so the new documents are searchable by document."]
open(os.path.join(WEB, "remaining.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"remaining.md: {len(SK)} uncatalogued files, {P(SK):,} pages")
